# -*- coding: utf-8 -*-
"""Test_using_model_sav.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cV-_A9V9LVpMcVfh4VJBfMLRQaEi1gyR
"""

from google.colab import drive
drive.mount('/content/drive')

import pickle
model1 = pickle.load(open("/content/drive/MyDrive/model.sav", "rb"))

from google.colab import files
uploaded =files.upload()
for fn in uploaded.keys():
  uploadedimagepath=f'/content/{fn}'

import cv2 as cv
from keras.preprocessing import image
img = image.load_img(uploadedimagepath, target_size = (224,224))
gray_image = cv.imread(uploadedimagepath)
gray_image = gray_image / 255
gray_image = cv.resize(gray_image, (224, 224))
gray_image = gray_image.reshape(-1, 224, 224, 3)

classes = ['aphids','armyworm','beetle','bollworm','grasshopper','mites','mosquito','sawfly','stem_borer']
prediction=model1.predict(gray_image)
a=prediction.reshape(-1)
list1 = a.tolist()
list1.index(max(list1))
#plt.xticks([])
#plt.yticks([])
#plt.imshow(img)
print(classes[list1.index(max(list1))])